### ISSUE TITLE
After i closed the app it just started throwing this error

### ISSUE THREAD

**Issue by khanakia** [CyanSalt/commas#23]
<img width="593" alt="Screenshot 2024-07-31 at 7 32 47 AM" src="https://github.com/user-attachments/assets/595c57b3-fb43-4ea5-a56e-41ed4d623010">

**Comment by CyanSalt** [comment]
I haven't been able to reproduce this problem. Perhaps the following is a solution based on some information I found.

> Your installation is affected by App Translocation. To fix this, either use the Finder and move the app to /Applications (or move it out of /Applications and then back in), or run the following terminal command:
>
> ```
> sudo xattr -dr com.apple.quarantine "/Applications/Commas.app"
> ```
