### ISSUE TITLE
[Help] Buttons are not working

### ISSUE THREAD

**Issue by tsengkasing** [CyanSalt/commas#3]
I downloaded the latest version of win32 but most of the buttons are not working.
Then I open the dev-tools and saw the errors.
What should I do? 

![image](https://user-images.githubusercontent.com/10103993/92387942-ff37ae80-f148-11ea-8ab2-25d82b7e7a5b.png)

**Comment by CyanSalt** [comment]
The Windows version has not been tested actually. I'll be working on it as soon as possible. Sorry about it.

As a temporary solution, you can build the app manually.

**Comment by tsengkasing** [comment]
Thanks.
